plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.pangziqiang.misharenolimit'
    compileSdk 34

    defaultConfig {
        applicationId "io.github.pangziqiang.misharenolimit"
        minSdk 29
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:101.0.1'
}
